feat: add postage check
ethersphere/beekeeper pull request #190
Opened 2021-08-19 14:39 UTC by aloknerurkar

- Create batch
- Top Up created batch
- Dilute batch

2021-09-19 19:24 UTC, acud requested changes

2021-09-19 19:24 UTC, acud commented on pkg/check/postage/postage.go
> +	PostageWait        time.Duration
no need for waits

2021-09-19 19:24 UTC, acud commented on pkg/check/postage/postage.go
> +		PostageWait:        5 * time.Second,
no need for this.

2021-09-19 19:24 UTC, acud commented on pkg/check/postage/postage.go
> +	time.Sleep(o.PostageWait)
the API will wait for you until the batch is usable

2021-09-19 19:24 UTC, acud commented on pkg/check/postage/postage.go
> +	time.Sleep(o.PostageWait)
here i would just hardcode a wait, then retry, since it is not guaranteed that the event is picked up after this sleep

2021-09-19 19:24 UTC, acud commented on pkg/check/postage/postage.go
> +	time.Sleep(o.PostageWait)
here too

2021-09-19 19:24 UTC, acud commented on pkg/check/postage/postage.go
> +	err = client.DilutePostageBatch(ctx, batchID, o.PostageNewDepth, o.GasPrice)
consider in both API wrappers to actually wait for the dilution to get picket up (by polling)

2021-09-20 08:55 UTC, mrekucci commented on pkg/beeclient/debugapi/postage.go
> +	url := fmt.Sprintf("/stamps/topup/%s/%d", batchID, amount)
I recommend to escape the `batchID` by using the `url.PathEscape()` function.

2021-09-20 08:56 UTC, mrekucci commented on pkg/beeclient/debugapi/postage.go
> +	url := fmt.Sprintf("/stamps/dilute/%s/%d", batchID, newDepth)
I recommend escaping the batchID by using the url.PathEscape() function.

2021-09-21 12:37 UTC, acud approved these changes
great stuff!

2021-09-21 12:51 UTC, mrekucci approved these changes

2021-09-21 12:53 UTC, merged